env_matrix: "env_matrix.yml"
channels: ['hcc']
upload_channel: "hcc"
# Channels ordered from highest to lowest priority. This should match the order
# of .condarc, but when adding channels using conda config --add, they should
# be added in reverse (from low to high priority).
channels:
    - t/TOKEN/hcc
    - hcc
    - conda-forge
    - conda-forge/label/cf201901
    - bioconda
    - defaults
docker_client_version: '1.20'
blacklists:
    - "blacklist"
